# Generated by Django 5.0.4 on 2024-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_number', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('preview1', models.CharField(max_length=200)),
                ('volume', models.CharField(max_length=200)),
                ('standard', models.CharField(max_length=200)),
                ('special_standard', models.CharField(max_length=200)),
                ('precision', models.CharField(max_length=200)),
                ('is_defective', models.BooleanField()),
                ('date_received', models.DateField()),
                ('spare1', models.CharField(blank=True, max_length=200, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='details/')),
            ],
        ),
    ]
