# Generated by Django 5.0.4 on 2024-05-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location_number',
            field=models.CharField(max_length=50),
        ),
    ]
