# Generated by Django 5.0.4 on 2024-05-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_passward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='week_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
