# Generated by Django 5.0.4 on 2024-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_day_time_user_week_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(default='사원', max_length=50),
        ),
    ]
