# Generated by Django 5.0.4 on 2024-05-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active_alter_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='week_time',
        ),
    ]
