# Generated by Django 5.0.4 on 2024-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_day_time_user_week_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='week_time',
            field=models.IntegerField(default=0),
        ),
    ]
