# Generated by Django 5.0.4 on 2024-05-21 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0005_alter_product_date_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RD', 'Ready'), ('MA', 'Maintenance'), ('TG', 'To the destination'), ('BH', 'Back to home'), ('UL', 'Unloading')], default='RD', max_length=2)),
                ('location', models.CharField(max_length=255)),
                ('battery', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('agv_camera', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255)),
                ('order_accepted', models.BooleanField(default=False)),
                ('destination', models.CharField(max_length=255)),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('estimated_time', models.DateTimeField(null=True)),
                ('agv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.agv')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OP', 'Operating'), ('RD', 'Ready'), ('MA', 'Maintenance')], default='ID', max_length=2)),
                ('is_operable', models.BooleanField(default=True)),
                ('rack_number', models.IntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
            ],
        ),
        migrations.AddField(
            model_name='agv',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order'),
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, through='api.Order_Product', to='products.product'),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.IntegerField()),
                ('status', models.CharField(choices=[('OP', 'Operating'), ('RD', 'Ready'), ('MA', 'Maintenance')], default='RD', max_length=2)),
                ('is_operable', models.BooleanField(default=True)),
                ('rack_camera', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], max_length=4)),
                ('target_object_id', models.PositiveIntegerField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('request_content', models.TextField()),
                ('response_content', models.TextField()),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
