# Generated by Django 5.0.4 on 2024-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_order_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_accepted',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Pending'), (1, 'Accepted'), (2, 'done'), (3, 'old')], default=0),
        ),
    ]
