# Generated by Django 5.0.4 on 2024-05-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='agv',
            name='agv_camera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='rack_camera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
