/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GeyXfahLYlR
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import { Input } from "@/components/ui/input"

export function ta() {
  return (
    (<div
      key="1"
      className="flex h-screen w-full flex-col bg-[#e0e0ff] dark:bg-[#2a2a3e]">
      <header
        className="flex h-16 w-full items-center justify-between bg-white px-4 shadow-md dark:bg-[#3c3c4f] md:px-6">
        <div className="flex items-center">
          <Link className="flex items-center" href="#">
            <MountainIcon className="h-6 w-6 text-[#5b5b8c] dark:text-white" />
            <span className="ml-2 text-xl font-bold text-[#5b5b8c] dark:text-white">Acme Inc</span>
          </Link>
        </div>
        <nav className="hidden items-center space-x-6 md:flex">
          <Link
            className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
            href="#">
            Home
          </Link>
          <Link
            className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
            href="#">
            Title 1
          </Link>
          <Link
            className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
            href="#">
            Title 2
          </Link>
          <Link
            className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
            href="#">
            Title 3
          </Link>
          <Link
            className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
            href="#">
            Title 4
          </Link>
        </nav>
        <Sheet>
          <SheetTrigger asChild>
            <Button className="md:hidden" size="icon" variant="outline">
              <MenuIcon className="h-6 w-6 text-[#5b5b8c] dark:text-white" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left">
            <div className="flex flex-col items-start space-y-6 p-6">
              <Link className="flex items-center" href="#">
                <MountainIcon className="h-6 w-6 text-[#5b5b8c] dark:text-white" />
                <span className="ml-2 text-xl font-bold text-[#5b5b8c] dark:text-white">Acme Inc</span>
              </Link>
              <nav className="flex flex-col items-start space-y-4">
                <Link
                  className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
                  href="#">
                  Home
                </Link>
                <Link
                  className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
                  href="#">
                  Title 1
                </Link>
                <Link
                  className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
                  href="#">
                  Title 2
                </Link>
                <Link
                  className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
                  href="#">
                  Title 3
                </Link>
                <Link
                  className="text-[#5b5b8c] hover:text-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:text-white dark:hover:text-[#606080] dark:focus:ring-[#707090] text-lg"
                  href="#">
                  Title 4
                </Link>
              </nav>
            </div>
          </SheetContent>
        </Sheet>
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-2">
            <ClockIcon className="h-5 w-5 text-[#5b5b8c] dark:text-white" />
            <span className="text-[#5b5b8c] dark:text-white">Weekly Hours: 40</span>
          </div>
          <div className="flex items-center space-x-2">
            <ClockIcon className="h-5 w-5 text-[#5b5b8c] dark:text-white" />
            <span className="text-[#5b5b8c] dark:text-white">Today's Hours: 8</span>
          </div>
          <Button
            className="rounded-md bg-[#9090c0] py-2 px-4 font-medium text-white hover:bg-[#7070b0] focus:outline-none focus:ring-2 focus:ring-[#9090c0] focus:ring-offset-2 dark:bg-[#707090] dark:hover:bg-[#606080] dark:focus:ring-[#707090]"
            variant="solid">
            Logout
          </Button>
        </div>
      </header>
      <div className="flex-1 p-6">
        <div className="flex flex-col md:flex-row items-start justify-between gap-6">
          <div className="flex flex-col gap-4">
            <div className="flex items-center justify-between">
              <Button size="icon" variant="outline">
                <ShoppingCartIcon className="h-5 w-5" />
                <span className="sr-only">View Cart</span>
              </Button>
              <div className="space-y-1">
                <h3 className="text-lg font-medium">Cart Items</h3>
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <img
                        alt="Product Image"
                        className="rounded-md"
                        height={40}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "40/40",
                          objectFit: "cover",
                        }}
                        width={40} />
                      <div>
                        <p className="font-medium">Product Name</p>
                        <p className="text-sm text-gray-500 dark:text-gray-400">$19.99</p>
                      </div>
                    </div>
                    <Button size="icon" variant="ghost">
                      <XIcon className="h-4 w-4" />
                      <span className="sr-only">Remove from cart</span>
                    </Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <img
                        alt="Product Image"
                        className="rounded-md"
                        height={40}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "40/40",
                          objectFit: "cover",
                        }}
                        width={40} />
                      <div>
                        <p className="font-medium">Another Product</p>
                        <p className="text-sm text-gray-500 dark:text-gray-400">$29.99</p>
                      </div>
                    </div>
                    <Button size="icon" variant="ghost">
                      <XIcon className="h-4 w-4" />
                      <span className="sr-only">Remove from cart</span>
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex flex-col gap-4 w-full">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <Button size="icon" variant="ghost">
                  <ChevronLeftIcon className="h-5 w-5" />
                  <span className="sr-only">Previous</span>
                </Button>
                <span className="font-medium">1</span>
                <Button size="icon" variant="ghost">
                  <ChevronRightIcon className="h-5 w-5" />
                  <span className="sr-only">Next</span>
                </Button>
              </div>
              <div className="relative w-full max-w-md">
                <SearchIcon
                  className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500 dark:text-gray-400" />
                <Input
                  className="w-full rounded-md border border-gray-200 bg-white px-3 py-2 pl-10 text-gray-900 shadow-sm focus:border-gray-400 focus:outline-none dark:border-gray-700 dark:bg-gray-950 dark:text-gray-50 dark:border-gray-800"
                  placeholder="Search products..."
                  type="search" />
              </div>
            </div>
            <div
              className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 overflow-x-auto scrollbar-hide">
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Product Name</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Another Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Third Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Fourth Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Fifth Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Sixth Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Seventh Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Eighth Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Ninth Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Tenth Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Eleventh Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
              <div className="flex flex-col gap-4">
                <img
                  alt="Product Image"
                  className="aspect-square rounded-md object-cover"
                  height={300}
                  src="/placeholder.svg"
                  width={300} />
                <div>
                  <h3 className="font-medium">Twelfth Product</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product description goes here.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function ClockIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
