/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qZAnC6BWK5N
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"

export function yes() {
  return (
    (<div className="container mx-auto px-4 py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Membership Management</h1>
        <div className="flex items-center space-x-4">
          <Button variant="outline">Add Member</Button>
          <Button>Export Data</Button>
        </div>
      </div>
      <div className="overflow-x-auto">
        <Table>
          <TableHeader className="bg-gray-100 dark:bg-gray-800">
            <TableRow>
              <TableHead className="font-medium">ID</TableHead>
              <TableHead className="font-medium">Name</TableHead>
              <TableHead className="font-medium">Rank</TableHead>
              <TableHead className="font-medium">Phone</TableHead>
              <TableHead className="font-medium">Username</TableHead>
              <TableHead className="font-medium">Day Time</TableHead>
              <TableHead className="font-medium">Week Time</TableHead>
              <TableHead className="font-medium">Is Active</TableHead>
              <TableHead className="font-medium">Is Staff</TableHead>
              <TableHead className="font-medium">Is Proven</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>001</TableCell>
              <TableCell>John Doe</TableCell>
              <TableCell>Gold</TableCell>
              <TableCell>123-456-7890</TableCell>
              <TableCell>johndoe</TableCell>
              <TableCell>12 hrs</TableCell>
              <TableCell>40 hrs</TableCell>
              <TableCell>
                <Checkbox defaultChecked id="is-active-1" />
              </TableCell>
              <TableCell>
                <Checkbox id="is-staff-1" />
              </TableCell>
              <TableCell>
                <Checkbox defaultChecked id="is-proven-1" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>002</TableCell>
              <TableCell>Jane Smith</TableCell>
              <TableCell>Silver</TableCell>
              <TableCell>987-654-3210</TableCell>
              <TableCell>janesmith</TableCell>
              <TableCell>8 hrs</TableCell>
              <TableCell>30 hrs</TableCell>
              <TableCell>
                <Checkbox id="is-active-2" />
              </TableCell>
              <TableCell>
                <Checkbox defaultChecked id="is-staff-2" />
              </TableCell>
              <TableCell>
                <Checkbox id="is-proven-2" />
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>003</TableCell>
              <TableCell>Bob Johnson</TableCell>
              <TableCell>Bronze</TableCell>
              <TableCell>555-555-5555</TableCell>
              <TableCell>bobjohnson</TableCell>
              <TableCell>6 hrs</TableCell>
              <TableCell>20 hrs</TableCell>
              <TableCell>
                <Checkbox defaultChecked id="is-active-3" />
              </TableCell>
              <TableCell>
                <Checkbox id="is-staff-3" />
              </TableCell>
              <TableCell>
                <Checkbox defaultChecked id="is-proven-3" />
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>)
  );
}
