# Generated by Django 5.0.4 on 2024-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_accepted',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Pending'), (1, 'Accepted')], default=0),
        ),
    ]
