# Generated by Django 5.0.4 on 2024-05-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_order_time_alter_order_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
